In [4]:
#2021.7.11

In [4]:
import numpy as np

In [5]:


li = [[[1,2,3],[4,5,6]],
      [[1,2,3],[4,5,6]]]

three_d_tensor = np.array(li, dtype=np.float32)
three_d_tensor

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)

In [6]:
three_d_tensor.ndim #3 ->3차원 텐서

3

In [7]:
three_d_tensor.shape #(2, 2, 3) -> 뒤에서부터 1차원요소(열), 2차원요소(행), 3차원요소(층?) 3차원이기때문에 3개의요소가 든 튜플반환.

(2, 2, 3)

In [8]:
three_d_tensor[0] #2차원까지만 반환

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
three_d_tensor[0].shape #3개의 열을가진 2개의 행

(2, 3)

In [10]:
three_d_tensor.__array_interface__ #메타정보를 한번에 관리하는 매직속성

{'data': (140666459554464, False),
 'strides': None,
 'descr': [('', '<f4')],
 'typestr': '<f4',
 'shape': (2, 2, 3),
 'version': 3}

In [11]:
three_d_tensor.strides #뒤에서부터 하나의원소(4byte=float32자료형이기 때문), 1차원배열(4*3 =12byte), 2차원배열(12*2= 24byte)를 나타냄.

(24, 12, 4)

In [12]:
print(three_d_tensor.data)
print()
print(three_d_tensor.data.tobytes())
print()
print(len(three_d_tensor.tobytes()))

#.data로 메모리박스(의주소값)를 가져온다. 메모리박스는 원소들을 1차원배열로 관리한다.
#.data.tobytes()로 메모리박스의 데이터를 가져온다.
#three_d_tensor는 총12개의 원소로 돼있다. = 48bytes(원소 1개당 4bytes(32bits) )


b'\x00\x00\x80?\x00\x00\x00@\x00\x00@@\x00\x00\x80@\x00\x00\xa0@\x00\x00\xc0@\x00\x00\x80?\x00\x00\x00@\x00\x00@@\x00\x00\x80@\x00\x00\xa0@\x00\x00\xc0@'

48


In [13]:
three_d_tensor.tolist() #일반 리스트로 변환

[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]]

In [14]:
print(three_d_tensor.data)
print()
a = np.array([[1,2,3],[4,5,6]])
mem = memoryview(a)
print(mem)

#data속성이 memoryview클래스로 만들어진것을 확인할 수 있다.
# https://docs.python.org/ko/3/library/stdtypes.html#memoryview 참조

In [15]:
print(three_d_tensor.data.obj)
print("--------------------")
print(mem.obj)

#.data속성을 사용해서 보여지는 것들은 전부 memoryview클래스로 만들어진 것이기 때문에  
#.data의 프로터티들은 전부 momoryview의 프로퍼티에서 따온것임을 짐작할 수 있다.

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]]
--------------------
[[1 2 3]
 [4 5 6]]


In [16]:
A = three_d_tensor.data[0:0]
B = three_d_tensor.data[0:1]
C = three_d_tensor.data[0:2]
D = three_d_tensor.data[0:0]

print(A.tolist())
print(B.tolist())
print(C.tolist())
print(A,B,C,D)

#1차원 인덱싱을하면 서브뷰를 만든다.

[]
[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]]
[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]]
<memory at 0x7fef99ba0310> <memory at 0x7fef99ba0400> <memory at 0x7fef99ba04f0> <memory at 0x7fef99ba05e0>


In [17]:
print(three_d_tensor.dtype) #자료형
print(three_d_tensor.itemsize) #단일원소 바이트
print(three_d_tensor.size) #원소의 총 개수(개)
print(three_d_tensor.data.hex()) 

#모든요소를 16진수로 변환(16진수는 4비트 단위로 숫자를표시, 두개의 16진수가 하나의 바이트)
#즉, 두개의 16진수 = 8개 문자 = 4바이트(32비트) = 원소 1개
a = three_d_tensor.data.hex()
len(a)

float32
4
12
0000803f0000004000004040000080400000a0400000c0400000803f0000004000004040000080400000a0400000c040


96

In [54]:
tda = [[[10, 20, 30], [11,22,33]],
       
       [[100, 200, 300], [111, 222, 333]],
       
       [[1000, 2000, 3000],[1111, 2222, 3333]]]

TDT = np.array(tda, dtype = np.float32)
TDT.shape

(3, 2, 3)

In [84]:
[i for i in TDT.flat if i < 100] #.flat속성을 사용하면 하나의 반복자를 제공한다.

[10.0, 20.0, 30.0, 11.0, 22.0, 33.0]

In [123]:
sub_TDT = np.frombuffer(TDT, dtype=np.float32)
print(sub_TDT) #1차원 배열로 뷰를 만들어준다.
print()
print(sub_TDT.reshape(3,2,3)) #TDT와 동일하게 reshape.

[  10.   20.   30.   11.   22.   33.  100.  200.  300.  111.  222.  333.
 1000. 2000. 3000. 1111. 2222. 3333.]

[[[  10.   20.   30.]
  [  11.   22.   33.]]

 [[ 100.  200.  300.]
  [ 111.  222.  333.]]

 [[1000. 2000. 3000.]
  [1111. 2222. 3333.]]]


In [109]:
print(sub_TDT.dtype)
print(sub_TDT.flags) # OWNDATA : False -> 새로운 배열이 만들어진게 아닌 뷰가 만들어진것 but, sub_TDT is TDT -> False

float32
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [113]:
print(sub_TDT.base)
sub_TDT.base is TDT
#뷰가 만들어지면 원본 배열의 정보가 base 속성에 들어간다. sub_TDT.base 와 TD의 레퍼런스가 같음.

[[[  10.   20.   30.]
  [  11.   22.   33.]]

 [[ 100.  200.  300.]
  [ 111.  222.  333.]]

 [[1000. 2000. 3000.]
  [1111. 2222. 3333.]]]


True

In [114]:
TDT.flags # OWNDATA : True

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [2]:
#2021.7.12

In [37]:
print(np.ndarray.__bases__)
print(np.matrix.__bases__)
#ndarray클래스는  object클래스만 상속했고, matrix클래스는 ndarray클래스를 상속한것

(<class 'object'>,)
(<class 'numpy.ndarray'>,)


In [59]:
tensr = np.array([1,2,3,4,5,6,7,8])
matrx = np.matrix([1,2,3,4,5,6,7,8])

print(tensr.shape)
print(matrx.shape)
#tensr는 1차원으로이지만 matrx는 2차원으로 처리가 된다.

(8,)
(1, 8)


In [61]:
print(tensr.reshape(2,4))
print(matrx.reshape(2,4))

print(tensr.reshape(2,4).shape)
print(matrx.reshape(2,4).shape)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
(2, 4)


In [65]:
print(tensr.reshape(2,2,2))

try:
    matrx.reshape(2,2,2)
except ValueError as vx:
    print(vx,"🤨")
    
#matrix클래스는 2차운인 행렬만 처리가능하다.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape too large to be a matrix. 🤨


In [73]:
np.asmatrix(tensr).reshape(2,4) #다차원 배열을 matrix클래스의 인스턴스로 변환이 가능하다.

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [75]:
tensr * tensr #다차원 배열의 곱셈은 같은 인덱스의 원소끼리 곱한 값이다. len이 같으면 가능하다는 뜻.

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [85]:
a = np.matrix([1,2,3,4]).reshape(2,2)
a * a

matrix([[ 7, 10],
        [15, 22]])

In [86]:
np.multiply(matrx, matrx)


#matrix곱셈은 행렬곱을 수행한다, 앞의 행렬의 열의 개수와 뒤 행렬의 행의 개수가 같은지 확인한다.
#np.multiply함수를 사용해서 matrix객체의 곱셈을 해결 할 수 있다.

matrix([[ 1,  4,  9, 16, 25, 36, 49, 64]])

In [102]:
nd_ = set(dir(np.ndarray))
md_ = set(dir(np.matrix))

md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [104]:
from numpy import linalg

In [111]:
mat = np.mat('1 2; 3 4')
print(mat)
print(linalg.inv(mat))
print(mat.I)

#넘파이 모듈에서 선형대수를 처리하려면 linalg모듈을 참조해야한다. inv함수로 역행렬을 계산한다.. 행렬객체에서는 단순히 I속성으로 확인도 된다.

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]
